[workspace]
changelog_update = false
git_release_enable = false
git_tag_enable = false

[[package]]
name = "graphql-ws-client"

git_tag_name = "v{{version}}"
git_tag_enable = true
git_release_enable = true

changelog_update = true
changelog_path = "./CHANGELOG.md"
