name: Publish to crates.io

on:
  push:
    tags: ["v*"]

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
    - name: Install markdown-extract
      shell: bash
      run: cargo install markdown-extract
    - uses: actions/checkout@v3
    - name: Generate changelog
      shell: bash
      run: markdown-extract --no-print-matched-heading "${{ github.ref_name }}" CHANGELOG.md > release-text.md
    - name: Make GitHub release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        body_path: ${{ github.workspace }}/release-text.md
  
  publish-crates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.72.1
      - name: Publish crate
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-release:
     needs: [generate-release, publish-crates]
     permissions:
       contents: write
     runs-on: ubuntu-latest
     env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - uses: actions/checkout@v3
       - name: mark release as non-draft
         run: |
           gh release edit ${{ github.ref_name }} --draft=false
